name: install and cache dependencies
description: install python packages (pip) from requirements and requirements_dev, and cache them
inputs:
  python-version:
    required: false
    default: '3.10'

runs:
  using: composite
  steps:
    - run: echo inputs.python-version
      shell: bash
    - name: python setup
      id: pydeps
      uses: actions/setup-python@v5
      with:
        python-version: inputs.python-version
        cache: 'pip'
        cache-dependency-path: 'requirements*.txt'

    - name: dependencies
      if: steps.pydeps.outputs.cache-hit == 'false'
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r requirements_dev.txt
      shell: bash
