name: code quality
on: [push, workflow_dispatch, workflow_call]
jobs:

  check-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: python setup
        id: pydeps
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'
      - name: dependencies
        if: steps.pydeps.outputs.cache-hit == 'false'
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r requirements_dev.txt

  lint:
    needs: check-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: python setup
        id: pydeps
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'
      - name: check black and mypy
        run: |
          python -m black --check src
          python -m mypy src

  test-unit:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    needs: check-cache
    name: run unit tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: python setup
        id: pydeps
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'
      - name: test code
        id: test
        run: python -m pytest tests/unit_tests
      - name: test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: log-unit-tests
          path: logs-unit

  test-module:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    needs: check-cache
    name: run module tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: python setup
        id: pydeps
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'
      - name: test code
        id: test
        run: python -m pytest tests/module_tests
      - name: test artifacts
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: log-module-tests
          path: logs-module

  all-pass:
    name: check if any filed
    needs: [lint, test-unit, test-module]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - run: echo "At least one of the previous jobs failed."
      - run: echo "Yes, this is stupid usage of jobs but I'm playing with worflows now and you can't stop me :)"
