name: code quality
on: [push, workflow_dispatch, workflow_call]
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/manage_dependencies
      - name: check black and mypy
        run: |
          python -m black --check src
          python -m mypy src

  test-unit:
    strategy:
      matrix:
        py_ver: ['3.7', '3.9', '3.10', '3.11', '3.13']
        os: [ubuntu-latest, windows-latest]
    name: run unit tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/manage_dependencies
        with:
          python-version: ${{ matrix.py_ver }}
      - name: test code
        id: test
        run: python -m pytest tests/unit_tests
      - name: test artifacts
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: log-unit-tests
          path: logs-unit

  test-module:
    strategy:
      matrix:
        py_ver: ['3.7', '3.9', '3.10', '3.11', '3.13']
        os: [ubuntu-latest, windows-latest]
    name: run module tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/manage_dependencies
        with:
          python-version: ${{ matrix.py_ver }}
      - name: test code
        id: test
        run: python -m pytest tests/module_tests
      - name: test artifacts
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: log-module-tests
          path: logs-module
