name: code quality
on: [push, workflow_dispatch]
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'
      - name: dependencies
        run: python -m pip install -r requirements_dev.txt
      - name: check black and mypy
        run: |
          python -m black --check src
          python -m mypy src

  test-unit:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dependencies
        run: python -m pip install -r requirements_dev.txt
      - name: test code
        run: python -m pytest tests/unit_tests
      - name: test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: log-unit-tests
          path: logs-unit

  test-module:
    name: run module tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dependencies
        run: python -m pip install -r requirements_dev.txt
      - name: test code
        run: python -m pytest tests/module_tests
      - name: test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: log-module-tests
          path: logs-module
