name: make docs with sphinx
on: [push]
jobs:

  make_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/manage_dependencies
      - name: prepare
        run: |
          echo "GG_VER=$(pip show GuiGen | grep 'Version: [0-9\.]*' | cut -f2 -d ' ')" >> $GITHUB_ENV
          # gg_ver="$(pip show GuiGen | grep 'Version: [0-9\.]*' | cut -f2 -d ' ')"
          mkdir docs
          cd docs
      - name: quickstart
        run: |
          sphinx-quickstart -q --ext-autodoc --ext-viewcode -p GuiGen -a "Filip Matejko" -v ${{ env.GG_VER }}
          echo "   modules" >> index.rst
      - name: document
        run: |
          sphinx-apidoc -o . ../src -d 2
      - name: build
        run: |
          make html
          cp _build/html/modules.html _build/html/index.html
          cd ..
      - name: save docs to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build/html
