name: make docs with sphinx
on: [push]
jobs:

  make_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create docs
        run: |
          pip install .
          gg_ver="$(pip show GuiGen | grep 'Version: [0-9\.]*' | cut -f2 -d ' ')"
          pip install -r requirements_dev.txt
          mkdir docs
          cd docs
          sphinx-quickstart -q --ext-autodoc --ext-viewcode -p GuiGen -a "Filip Matejko" -v $gg_ver --master modules
          rm modules.rst
          sphinx-apidoc -o . ../src -d 2
          make html
          cp _build/html/modules.html _build/html/index.html
          cd ..
      - name: save docs to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build/html
