name: code quality
on: [push, workflow_dispatch]
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: intall dependencies
        run: |
          pip install .
          pip install -r requirements_dev.txt
      - name: test code
        run: |
          python -m black --check src
          python -m mypy src
  test:
    name: test the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: intall dependencies
        run: |
          pip install .
          pip install -r requirements_dev.txt
      - name: test code
        run: python -m pytest ./tests
